### ISSUE TITLE
Use syntax highlighting for code blocks

### ISSUE THREAD

**Issue by dbohdan** [tclssg/tclssg#58]

**Comment by mpcjanssen** [comment]
Out of the box, TclSSG doesn't support code highlighting. Adding it is trivial though.

With the commit adding code blocks with language classes to the markdown parser, adding code highlighting using highlightjs is trivial.

Download highlighjs with the required languages from https://highlightjs.org/download/.
Extract the highlightjs bundle in the `/static/vendor` directory of the website.
Add the required css and js includes to the html headers.
For each applicable preset in `/presets` at the following stanza:

``` tcl
{head top} {
<link rel="stylesheet" href="/vendor/highlightjs/styles/github.css">
<script src="/vendor/highlightjs/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
}
```
You can replace github with any supported style.

**Comment by dbohdan** [comment]
@mpcjanssen Thanks!  I've converted your comment to a [wiki page](https://github.com/tclssg/tclssg/wiki/Syntax-highlighting).  I'm closing the issue now.
