### ISSUE TITLE
Ability to customize which Markdown processor is used

### ISSUE THREAD

**Issue by apnadkarni** [tclssg/tclssg#63]
I would like the ability to specify which markdown processor is used for processing the markdown text. The Caius based one is decent but does not handle all embedded HTML fragments. 

~As a generalization, ability to support multiple processors (markdown, asciidoc etc.) would be even better, based on the file extension for example.~ -->  #65

**Comment by dbohdan** [comment]
I made a separate issue for your second paragraph.

**Comment by dbohdan** [comment]
Done in 60c1a463281d93db63c808988d1bcac588448593.
