### ISSUE TITLE
Extraneous literal \n on Windows

### ISSUE THREAD

**Issue by apnadkarni** [tclssg/tclssg#69]
If the input file has Windows style CR-LF line endings, the first line after the page header block has a literal \n (i.e. literal backslash, followed by letter n) tacked on to the corresponding output fragment. For example, if page input is

````
{
   description {Some description}
}
This is line 1.
This is line 2.
````

Output is

````
This is line 1.\nThis is line 2.
````
This happens only with the first line. Rest of page is ok.

**Comment by dbohdan** [comment]
Does this bug reproduce after `dos2unix`/when the repo is checked out with LF line endings?

**Comment by apnadkarni** [comment]
Yes. Also with the beta distribution. There are two issues - one is that if the tclssg package files have crlf endings, you get the error I reported on the chat - " settings {head top}.. command not found". That error is fixed by changing the tclssg scripts to LF line endings. 

Fixing this error requires the web pages themselves to have LF line endings.

Hope that's clear.

**Comment by dbohdan** [comment]
Please check the branch `newlines` and tell me if it addresses both issues.

**Comment by apnadkarni** [comment]
Look good. Both issues seem fixed.
