### ISSUE TITLE
HTML entities are garbled in output

### ISSUE THREAD

**Issue by apnadkarni** [tclssg/tclssg#70]
I used the `&#x2605;` HTML entity to display stars. This was displayed correctly in tclssg 0.9. In 2.0-beta-2 as well as the newlines branch, this displays as garbled fonts.

**Comment by dbohdan** [comment]
Is this a Tclssg pipeline or a Bootstrap/browser issue?  I can't reproduce it with the following input file.

```markdown
{
    title test
    blogPost 1
}
&#x2605;&#x2605;&#x2605;
```

It is transformed into the following HTML and renders correctly for me with `font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;`.

```HTML
...
          <section class="col-md-8">
            <header><h1 class="page-title">test</h1></header><p>&#x2605;&#x2605;&#x2605;</p>
            
          </section>
...
```

Please attach an input file (`foo.md`) that gets corrupted and its output HTML file and preferably screenshot.

**Comment by apnadkarni** [comment]
Found the problem. It only happens if the tidy option is enabled. If tidy is disabled, it shows up fine.

So not sure if this should be logged as a bug or not.

**Comment by dbohdan** [comment]
I've pushed a possible fix to the `dev` branch.

**Comment by dbohdan** [comment]
Tell me when you're done upgrading and I'll publish a new beta release.

**Comment by apnadkarni** [comment]
All seems fine now. No obvious errors in output that I can see.
