### ISSUE TITLE
deployCustom command works differently in 2.0

### ISSUE THREAD

**Issue by apnadkarni** [tclssg/tclssg#71]
Not necessarily a bug but just so you are aware...

In 0.9, the following deployCustom command used to work for me (Windows)

```
pscp -C -r -v "$outputDir/*" apnmbx-wits@magicsplat.com:/var/www/magicsplat
```
In 2.0 beta it raises an error that key "$outputDir/*" (exact error below). I had to change the command to
```
pscp -C -r -v "$outputDir" apnmbx-wits@magicsplat.com:/var/www/magicsplat
```
which works but has different semantics requiring an additional step after the copy and is less convenient.

Just FYI in case it points to some other more significant issue.

The exact error stack was
```
---- 2019-11-10 11:14:37 IST [error]

*** error: key "outputDir/*" not known in dictionary ***
Traceback:
key "outputDir/*" not known in dictionary
    while executing
"dict get $substDict $key"
    ("uplevel" body line 4)
    invoked from within
"uplevel 1 $script"
    (procedure "::struct::list::Lmapfor" line 8)
    invoked from within
"::struct::list::Lmapfor x {pscp -C -r -v "$outputDir/*" apnmbx-wits@magicsplat.com:/var/www/magicsplat} {
```

**Comment by dbohdan** [comment]
I've reverted the `deployCustom` variable substitution to (a subset of) its old behavior.  Please check `dev`.

**Comment by dbohdan** [comment]
Updated.  I think I have found a nice compromise between the old and the new semantics.

**Comment by apnadkarni** [comment]
Works for me. Thanks.

magicsplat is running the updated code.

**Comment by dbohdan** [comment]
Great! Thank you for your bug reports. If I get no new issues for a few days I'll release a new beta.
