### ISSUE TITLE
Tcl9 does not support "-encoding binary" anymore 

### ISSUE THREAD

**Issue by PaulObermeier** [tclssg/tclssg#76]
See [Migrating scripts to Tcl 9](https://core.tcl-lang.org/tcl/wiki?name=Migrating%20scripts%20to%20Tcl%209)
Chapter **Removal of binary and the empty string as valid values for the -encoding setting for channels**

**Comment by dbohdan** [comment]
Thanks for the heads-up! I have pushed a fix in f30f045c5c38d14e94db4306f7282b6d0dd65d11. Could you test it and tell me if it works for you?

**Comment by PaulObermeier** [comment]
Thanks for the quick fix.
I could successfully create my tcl3d sites using Tcl9.0.b3.

**Comment by dbohdan** [comment]
Great! Thanks for testing. I have released [v2.3.1](https://github.com/tclssg/tclssg/releases/tag/v2.3.1).

**Comment by PaulObermeier** [comment]
You forgot to update "variable version" in ssg.tcl.

**Comment by dbohdan** [comment]
Oops! Fixed. I have force-updated the tag.
